name: Crowdin download

on:
  schedule:
    - cron: '0 3 * * 0'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  download-l10n-from-crowdin:
    runs-on: ubuntu-latest
    env:
      DEFAULT_BRANCH: ${{ github.event.repository.default_branch || 'master' }}
      PR_TOKEN: ${{ secrets.KIREIBPM_CI_PAT != '' && secrets.KIREIBPM_CI_PAT || github.token }}
      CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
      CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ env.PR_TOKEN }}

      - name: Install crowdin-cli
        run: |
          sudo wget -qO - https://artifacts.crowdin.com/repo/GPG-KEY-crowdin | sudo apt-key add -
          sudo touch /etc/apt/sources.list.d/crowdin.list
          sudo add-apt-repository "deb https://artifacts.crowdin.com/repo/deb/ /" 
          sudo apt-get update && \
          sudo apt-get install -y --no-install-recommends \
          crowdin3 \
          apt-transport-https

      - name: Download l10n
        run: crowdin pull -b "$DEFAULT_BRANCH" -l fr -l ja -l es-ES -l pt-BR --no-progress

      - name: Configure git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        id: create-pr
        with:
          token: ${{ env.PR_TOKEN }}
          branch: feat/${{ env.DEFAULT_BRANCH }}/update-translations
          base: ${{ env.DEFAULT_BRANCH }}
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          commit-message: "chore(l10n) update translations"
          title: "[${{ env.DEFAULT_BRANCH }}] Translations update"
          body: |
            Latest translations made in Crowdin for KireiBPM web components.